spring:
  application:
    name: clothes-admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:2002
server:
  port: 2002 
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000  # feign 超时控制
clothes-system-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  # SR6版本,这里设为1,会重试3次,重试次数还和另外的两个值有关
